site_name: Rosaninha — Documentação
site_url: https://alissonluana.github.io/rosaninha/
repo_url: https://github.com/AlissonLuana/rosaninha
docs_dir: docs

theme:
  name: material
  language: pt-BR
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    scheme: default

plugins:
  - search:
      lang: pt

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
